#!/bin/bash

######  Created by:
######  Patrick Hart
######  thrifus@gmail.com
######  http://thrifus.co/
######  http://github.com/thrifus/Tortle

######  Tortle version 1.0.?

BOLD=$(tput bold)
NORM=$(tput sgr0)

proxyAddress="127.0.0.1"
proxyPort="9050"

enableTor="0"
disableTor="0"

while [ "$1" != "" ]; do
case $1 in
	-e | --enable )     enableTor="1"
	                break ;;
	-d | --disable )    disableTor="1"
	                break ;;
	* )                 exit 0
esac
done

if [ "$enableTor" = "1" ]
then
	tor --runasdaemon 1 & wait tor &
	sudo networksetup -setsocksfirewallproxy Wi-Fi $proxyAddress $proxyPort
	sudo networksetup -setsocksfirewallproxystate Wi-Fi on
	echo -e "\n\033[1mRestarting your network...\033[0m"
	sudo networksetup -setairportpower en0 off
	sudo networksetup -setairportpower en0 on
	echo -e "${BOLD}Tor is now enabled and SOCKS proxy has been enabled to use Tor.${NORM}\n"
	exit 0
elif [ "$disableTor" = "1" ]
then
sudo bash <<'INJECT'
	sudo killall -9 tor
	sudo networksetup -setsocksfirewallproxystate Wi-Fi off
	echo -e '\n\033[1mRestarting your network...\033[0m'
	sudo networksetup -setairportpower en0 off; networksetup -setairportpower en0 on
INJECT
	echo -e "${BOLD}Tor has been stopped and SOCKS proxy has been disabled.${NORM}\n"
	exit 0
elif [ "$1" = "" ]
then
	echo -e "${BOLD}Usage: tortle [-e or --enable to enable ] [-d or --disable to disable]${NORM}"
fi
