#!/bin/bash

######  Created by:
######  Patrick Hart
######  thrifus@gmail.com
######  http://thrifus.co/
######  http://github.com/thrifus/Tortle

######  Tortle version 1.0.8

## Makes bold and normal text, much easier than writing ${bold} text ${normal} every time
bold=$(tput bold)
normal=$(tput sgr0)
## Should be self explanatory, if not, it's the config file for Tor
torccFile=/usr/local/etc/tor/torcc
## Arguments
enableTor=
disableTor=

## Setup the arguments
while [ "$1" != "" ]; do
case $1 in
    -e | --enable )     enableTor=1
                        break ;;
    -d | --disable )    disableTor=1
                        break ;;
    * )                 exit 0
esac
done

## Check the arguments
if [ "$enableTor" = "1" ]
then
## Run Tor as a daemon so we don't have to keep the window open
    tor --runasdaemon 1 -f $torccFile
## Inject the following commands (which need root) into a Bash shell
sudo bash <<'INJECT'
    ## Self explanatory
    proxyAddress=127.0.0.1
    ## Also self explanatory
    proxyPort=9050

    ## Set the SOCKS proxy
    sudo networksetup -setsocksfirewallproxy Wi-Fi $proxyAddress $proxyPort

    ## Set the SOCKS proxy to on
    sudo networksetup -setsocksfirewallproxystate Wi-Fi on

    ## Restart network to ensure proxy connections
    echo -e '\033[1mRestarting your network...\033[0m'
    echo
    sudo networksetup -setairportpower en0 off; networksetup -setairportpower en0 on
INJECT
    echo -e "${bold}Tor is now enabled and SOCKS proxy has been enabled to use Tor.${normal}"
    exit 0
elif [ "$disableTor" = "1" ]
then
## Inject the following commands (which need root) into a Bash shell
sudo bash <<'INJECT'
    ## Kill Tor
    sudo killall -9 tor

    ## Set the SOCKS proxy to off
    sudo networksetup -setsocksfirewallproxystate Wi-Fi off

    ## Restart network to ensure proxy connections
    echo -e '\033[1mRestarting your network...\033[0m'
    echo
    sudo networksetup -setairportpower en0 off; networksetup -setairportpower en0 on
INJECT
    echo -e "${bold}Tor has been stopped and SOCKS proxy has been disabled.${normal}"
    exit 0
elif [ "$1" = "" ]
then
    echo -e "${bold}Usage: tortle [-e or --enable to enable ] [-d or --disable to disable]${normal}"
fi
